### ISSUE TITLE
TemplateError has no details during rendering

### ISSUE THREAD

**Issue by foxbunny** [Outernet-Project/librarian-dashboard#1]
When dashboard plugin is rendered, if there is a TemplateError, the traceback looks something like:

```
Plugin rendering failed: ondd
Traceback (most recent call last):
  File "/home/hajime/code/librarian-dashboard/librarian_dashboard/dashboard.py", line 89, in render
    return template(self.get_template(), **context)
  File "/home/hajime/.envs/libtest/bin/bottle.py", line 3588, in template
    TEMPLATES[tplid] = adapter(name=tpl, lookup=lookup, **settings)
  File "/home/hajime/.envs/libtest/bin/bottle.py", line 3209, in __init__
    raise TemplateError('Template %s not found.' % repr(name))
TemplateError
```

It is impossible to tell what the missing template is. Dashboard code should trap the exception and print the exact template that is missing.

**Comment by foxbunny** [comment]
it's being logged.
